project_id = "dkxvmorjwoqtrspbrztr"

[functions.send-invoice-email]
verify_jwt = false

[functions.calendar-ical]
verify_jwt = false

[functions.authentik-callback]
verify_jwt = false

[functions.authentik-login]
verify_jwt = false
